freeze: true
project:
  type: book

book:
  title: "Bash for HPC"
  author: "Ted Laderas"
  date: "4/22/2024"
#  google-analytics: "G-QM3D3CT5J5"
  chapters:
    - index.qmd
    - "hpc-basics.qmd"
    - "intro-unix.qmd"
    - "running-stuff.qmd"
    - "scripting-basics.qmd"
    - "interactive_shell.qmd"
#    - "04-doing-work-with-dx-run.qmd"
#    - "05-batch-processing.qmd"
#    - "06-JSON.qmd"
#    - "07-containers.qmd"
#    - "appendix.qmd"
#    - references.qmd
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt
